#!/bin/sh
ssh ubuntu@http://ec2-43-200-57-202.ap-northeast-2.compute.amazonaws.com/ <<EOF
    cd ~/nodejs-jenkins
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 18.9.0
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF